Add Intel H2312XXKR2 Blade Chassis
netbox-community/devicetype-library pull request #1180
Opened 2023-03-07 16:38 UTC by getspaghett

Added Intel H2312XXKR2 Blade Chassis definition with specifications taken from [intel.com](https://www.intel.com/content/www/us/en/products/sku/81877/intel-server-chassis-h2312xxkr2/specifications.html)

2023-03-08 20:22 UTC, danner26 requested changes

2023-03-08 20:22 UTC, danner26 commented on device-types/Intel/H2312XXKR2.yaml
> +subdevice_role: parent
Please add `airflow` if you have it

2023-03-08 20:22 UTC, danner26 commented on device-types/Intel/H2312XXKR2.yaml
> +power-ports:
Just as in the other one, the PSUs are modular. This definition should be removed and `module-bays` should be created
Then create the applicable PSUs in the module-types folder

Looks like the PSUs are `FXX1600PCRPS`

2023-03-09 15:54 UTC, danner26 commented
Hello, unfortunately today we had to make a change to the schema in which weight is defined by. The upstream NetBox API requires weight to be passed to it in the following format:
```
weight: 12.01
weight_unit: lb
```

Due to this change, I have updated your branch against the current master. This might require you to update your PR, if you had weight currently defined, so that your PR is in-line with the new weight schema. If you have any issues, please let me know or refer to [this PR](https://github.com/netbox-community/devicetype-library/pull/1187) for more information.

2023-03-09 18:16 UTC, danner26 commented
Anything else needed for this PR?

2023-03-10 07:29 UTC, getspaghett commented
> Anything else needed for this PR?

Nope, i think it is ready to be merged :) :+1:

2023-03-10 14:36 UTC, danner26 approved these changes

2023-03-10 14:36 UTC, merged