Add and fix several Cisco device types
netbox-community/devicetype-library pull request #1181
Opened 2023-03-07 17:36 UTC by desnoe

2023-03-08 19:57 UTC, danner26 commented
Please fix all tests @desnoe and then ping me once they are all passing. In the meantime I will revert this PR to a draft state

2023-03-08 21:35 UTC, desnoe commented
@danner26 all tests are now passing

2023-03-09 15:54 UTC, danner26 commented
Hello, unfortunately today we had to make a change to the schema in which weight is defined by. The upstream NetBox API requires weight to be passed to it in the following format:
```
weight: 12.01
weight_unit: lb
```

Due to this change, I have updated your branch against the current master. This might require you to update your PR, if you had weight currently defined, so that your PR is in-line with the new weight schema. If you have any issues, please let me know or refer to [this PR](https://github.com/netbox-community/devicetype-library/pull/1187) for more information.

2023-03-10 08:00 UTC, desnoe commented
No problem @danner26 it seems to be passing all tests.

2023-03-12 01:23 UTC, danner26 commented
Hey @desnoe all devices from now on should have their manufacturer name appended to their slugs. I.E. `cisco-` in this case. Can you please make sure that modification is made? Thank you

2023-03-17 08:59 UTC, desnoe commented
> Hey @desnoe all devices from now on should have their manufacturer name appended to their slugs. I.E. `cisco-` in this case. Can you please make sure that modification is made? Thank you

This is now fixed.

2023-03-20 04:10 UTC, danner26 requested changes
Here are my initial comments, please notate if you dont have information requested and then you can resolve it.. Otherwise please add the applicable information then resolve it. Thanks!

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C2960XR-24TD-I.yaml
> +    type: iec-60320-c14
You dont define PSU type in the module bay, that is part of the module-type file

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C2960XR-24TD-I.yaml
> +    type: iec-60320-c14
You dont define PSU type in the module bay, that is part of the module-type file

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C2950G-24-EI.yaml
> +    maximum_draw: 45
Dont these have a DC secondary power supply port? Specifically for a 14 pin DC terminal? If so, please add a power port with `dc-terminal` type

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C2950G-24-EI.yaml
> +is_full_depth: false
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C2950G-24-EI-DC.yaml
> +is_full_depth: false
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/NCS-57B1-5DSE-SYS.yaml
> +is_full_depth: true
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/N3K-C3548P-10G.yaml
> +is_full_depth: false
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/ME-3400EG-12CS-M.yaml
> +u_height: 1
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/ASAv.yaml
> +u_height: 0
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/ASAv.yaml
> +u_height: 0
Does this device have any ports? Or was this just not finished yet?

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/ASA5515.yaml
> +u_height: 1
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C2970G-24TS-E.yaml
> +is_full_depth: false
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C3550-12T.yaml
> +is_full_depth: false
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C3560G-24TS-E.yaml
> +u_height: 1
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C3560G-48TS-E.yaml
> +u_height: 1
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C3560V2-48TS-E.yaml
> +u_height: 1
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C3560X-24T-L.yaml
> +u_height: 1
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C3750X-24S-S.yaml
> +u_height: 1
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C4510R.yaml
> +is_full_depth: true
Do you have `weight`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C4510R.yaml
> +is_full_depth: true
Do you have `airflow`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C3750X-24S-S.yaml
> +u_height: 1
Do you have `airflow`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C3560X-24T-L.yaml
> +u_height: 1
Do you have `airflow`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C3560V2-48TS-E.yaml
> +u_height: 1
Do you have `airflow`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C3560G-48TS-E.yaml
> +u_height: 1
Do you have `airflow`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C3560G-24TS-E.yaml
> +u_height: 1
Do you have `airflow`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C3550-12T.yaml
> +is_full_depth: false
Do you have `airflow`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C2970G-24TS-E.yaml
> +is_full_depth: false
Do you have `airflow`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C2950G-24-EI.yaml
> +is_full_depth: false
Do you have `airflow`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/WS-C2950G-24-EI-DC.yaml
> +is_full_depth: false
Do you have `airflow`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/NCS-57B1-5DSE-SYS.yaml
> +is_full_depth: true
Do you have `airflow`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/N3K-C3548P-10G.yaml
> +is_full_depth: false
Do you have `airflow`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/ME-3400EG-12CS-M.yaml
> +u_height: 1
Do you have `airflow`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/ASAv.yaml
> +u_height: 0
Do you have `airflow`? If so, please add it

2023-03-20 04:10 UTC, danner26 commented on device-types/Cisco/ASA5515.yaml
> +u_height: 1
Do you have `airflow`? If so, please add it

2023-04-28 04:01 UTC, closed without merging