Contributes 6 new device types for Nokia SR Linux product line
netbox-community/devicetype-library pull request #1189
Opened 2023-03-10 19:21 UTC by jbemmel

* D1 (management switch)
* D2/D2L
* D3/D3L
* H3

All systems come in AC and DC variants, with airflow Front-2-Back or Back-2-Front

2023-03-12 18:00 UTC, danner26 requested changes
Hello, thank you for your contribution! Please review the requested changes and let me know if you have any questions. In the meantime I am going to mark this PR as a draft, and once you are ready you can mark it ready for review and ping me if desired.

2023-03-13 00:19 UTC, jbemmel commented on device-types/Nokia/7220-IXR-H3.yaml
> +is_full_depth: true  # 21.65"
All devices come in 2 variants: Front-2-back and Back-2-front. Does that mean we would have to model each separately? (leading to x2 duplication of the same information)

Similar question for DC/AC variants, should we model those as separate device types?

2023-03-13 00:25 UTC, danner26 commented on device-types/Nokia/7220-IXR-H3.yaml
> +is_full_depth: true  # 21.65"
@jbemmel do the devices have different model numbers based on airflow direction? There are a handful of devices that are like this and indeed they are duplicated (besides airflow) with their specific model numbers being the differentiation

In regards to the AC/DC variants, again those PSUs appear to be modular. In this case the device should be modelled as is. Then in this file you make the PSUs module-bays, and create the PSUs as module-types as described in my other comments

2023-03-13 16:02 UTC, jbemmel commented on device-types/Nokia/7220-IXR-D1.yaml
> +is_full_depth: false  # 15.75"
added in modules

2023-03-13 16:02 UTC, jbemmel commented on device-types/Nokia/7220-IXR-D2.yaml
> +is_full_depth: false  # 18.11"
no, not available

2023-03-13 16:02 UTC, jbemmel commented on device-types/Nokia/7220-IXR-D2.yaml
> +is_full_depth: false  # 18.11"
added in modules

2023-03-13 16:03 UTC, jbemmel commented on device-types/Nokia/7220-IXR-D2L.yaml
> +is_full_depth: true  # 21.10"
no, not available

2023-03-13 16:03 UTC, jbemmel commented on device-types/Nokia/7220-IXR-D3.yaml
> +is_full_depth: false  # 18.11"
no, not available

2023-03-13 16:03 UTC, jbemmel commented on device-types/Nokia/7220-IXR-D3L.yaml
> +is_full_depth: true  # 21.28"
no, not available

2023-03-13 16:03 UTC, jbemmel commented on device-types/Nokia/7220-IXR-H3.yaml
> +is_full_depth: true  # 21.65"
no, not available

2023-03-13 16:04 UTC, jbemmel commented on device-types/Nokia/7220-IXR-H3.yaml
> +is_full_depth: true  # 21.65"
ok, modeled both PSUs and fans as modules

2023-03-13 16:07 UTC, jbemmel commented
Looks like the system does not allow 'airflow' attribute for fan modules, but these modules do have a specific airflow direction - it is essential to their existence

Could we update Netbox to allow airflow attributes for modules?

2023-03-13 17:12 UTC, danner26 commented
Yup I agree, for the time being to get this PR moving, could you just create the modules without airflow? You could also add a comment with the airflow direction so that once this is possible we can retroactively go back and fix these

2023-03-13 17:22 UTC, jbemmel commented on device-types/Nokia/7220-IXR-D2L.yaml
> +is_full_depth: true  # 21.10"
as discussed, airflow is specific to the PSU/fan modules

2023-03-13 18:07 UTC, danner26 commented
Hey @jbemmel I would recommend adding `position` to the module-types. When a module referenced `{module}` it will use what is in position
For example if your module is `- name: PSU{module}` and you install it to a slot with `position: 3`, you will end up with  `PSU3`

Let me know if you need help with this. If you, please send me an invite to your fork

2023-03-13 19:25 UTC, danner26 commented
Just a reminder the positions need to be strings, so you need to write them as `'1'`

2023-03-14 13:17 UTC, danner26 approved these changes

2023-03-14 13:18 UTC, merged