Add Synology DS1821+ device type
netbox-community/devicetype-library pull request #1203
Opened 2023-03-15 12:59 UTC by nemccarthy

Synology DS1821+

2023-03-15 13:48 UTC, danner26 requested changes

2023-03-15 13:48 UTC, danner26 commented on device-types/Synology/ds1821+.yaml
> +slug: ds1821plus
please append `synology-` to the slug

2023-03-15 13:48 UTC, danner26 commented on device-types/Synology/ds1821+.yaml
> +u_height: 4
This is not a rack mounted device, please make `u_height` set to `0`

2023-03-16 04:46 UTC, nemccarthy commented
thanks @danner26 changes have been made as suggested!

2023-03-16 19:55 UTC, danner26 approved these changes

2023-03-16 19:55 UTC, merged