PAN-PA-5400-MPC-A.yaml
netbox-community/devicetype-library pull request #1286
Opened 2023-04-13 03:48 UTC by kalazzawi

2023-04-13 13:49 UTC, danner26 requested changes

2023-04-13 13:49 UTC, danner26 commented
Please note, you do not need to put `mgmt_only: false`

2023-04-14 11:47 UTC, kalazzawi reviewed
part_number: PAN-PA-5400-MPC-A

2023-04-14 11:54 UTC, kalazzawi commented on module-types/Palo Alto/PAN-PA-5400-MPC-A.yaml
> +model: PAN-PA-5400-MPC-A
part_number: PAN-PA-5400-MPC-A

2023-04-14 11:56 UTC, kalazzawi reviewed
part_number: PAN-PA-5400-MPC-A

2023-04-15 04:39 UTC, kalazzawi commented
Please review at your earliest convenience.

On Thu, Apr 13, 2023 at 9:49 AM Daniel W. Anner ***@***.***>
wrote:

> Please note, you do not need to put mgmt_only: false
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/netbox-community/devicetype-library/pull/1286#issuecomment-1506997627>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEEO7D344HRSCZYZAXR4VZ3XA777RANCNFSM6AAAAAAW4QCI6U>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-15 14:32 UTC, danner26 approved these changes

2023-04-15 14:32 UTC, merged