Add QNAP TS-EC1280U
netbox-community/devicetype-library pull request #1294
Opened 2023-04-14 18:06 UTC by Madrov

2023-04-15 14:54 UTC, danner26 requested changes

2023-04-15 14:54 UTC, danner26 commented on device-types/QNAP/TS-EC1280U.yaml
> +device-bays:
Currently NetBox is not utilized for storage management. We have that feature in planning, but it is not currently ready. Please remove the disk definitions and `device-bays`

2023-04-15 14:54 UTC, danner26 commented on device-types/QNAP/TS-EC1280U.yaml
> +subdevice_role: parent
This is generally used for chassis which house other devices, this is not meant for devices with modules. Is this actually needed, and if so why are there no `device-bays`?

2023-04-15 23:51 UTC, Madrov commented
I made the adjustments. Thank you 🙂

2023-04-16 15:23 UTC, danner26 approved these changes

2023-04-16 15:23 UTC, merged