added extreme networks x450 g2 48p 10ge4
netbox-community/devicetype-library pull request #1297
Opened 2023-04-14 19:17 UTC by WagoL

added extreme networks x450 g2 48p 10ge4.

2023-04-15 14:51 UTC, danner26 requested changes

2023-04-15 14:51 UTC, danner26 commented on device-types/Extreme Networks/X450-G2-48p-10GE4.yaml
> +subdevice_role: parent
This is generally used for chassis which house other devices, this is not meant for devices with modules. Is this actually needed, and if so why are there no `device-bays`?

2023-04-17 07:24 UTC, WagoL commented
I removed the subdevice.

2023-04-26 13:10 UTC, danner26 approved these changes

2023-04-26 13:11 UTC, merged