Add Fortinet FG-3300E, FG3301E and SP-RACKTRAY-02
netbox-community/devicetype-library pull request #1299
Opened 2023-04-16 04:50 UTC by Madrov

2023-04-16 15:30 UTC, danner26 requested changes

2023-04-16 15:30 UTC, danner26 commented on device-types/Fortinet/SP-RACKTRAY-02.yaml
> +slug: sp-racktray-02
The slug should have the manufacturer appended to it. Please append `fortinet-`

2023-04-21 22:57 UTC, Madrov commented
@danner26 I do not know if you have received the notification about the review request, but it's ready 🙂 

Thank you!

2023-04-26 13:30 UTC, danner26 approved these changes
Looks good now, sorry about that has been backed up

2023-04-26 13:31 UTC, merged