Add server Dell PowerEdge R240
netbox-community/devicetype-library pull request #1304
Opened 2023-04-19 06:34 UTC by davidusken

https://www.dell.com/en-us/shop/enterprise-products/r240-1ru-server-intel/spd/poweredge-r240

2023-04-21 19:14 UTC, danner26 requested changes

2023-04-21 19:14 UTC, danner26 commented on device-types/Dell/PowerEdge_R240.yaml
> +power-ports:
Is this PSU modular? If so, this should be modelled in a `module-bays`, and then the applicable PSU should be added to the module-types folder

2023-04-21 19:14 UTC, danner26 commented on device-types/Dell/PowerEdge_R240.yaml
> +  - name: VGA
VGA is not a console port, please remove this

2023-05-16 06:27 UTC, davidusken commented
Ok thanks, Dell EMC PowerEdge R240 comes with 2 different options for PSUs. It is changeable but requires opening the cover, removing a screw, and disconnecting the cables. Here is a screenshot of the PSU specifications:

![image](https://github.com/netbox-community/devicetype-library/assets/16537412/90fe5186-e52f-40c5-a048-8496edc90195)

Would you prefer this to be added as modules still or have 2 different model versions of the server?

2023-05-16 14:58 UTC, danner26 commented
Do the devices have different part numbers based on which PSU is installed?

2023-06-29 04:01 UTC, closed without merging