Add Juniper EX4100 device types modified from EX3400 models
netbox-community/devicetype-library pull request #1310
Opened 2023-04-20 00:16 UTC by twilley

These are based on the EX3400 device types.

2023-04-24 17:15 UTC, twilley commented
@danner26 I'm modeling that now, and I will commit soon.  Is there a solution I'm not aware of to provide the preinstallation of modules within the module bays when the device is created? I would love to see a way to provide pre-installed modules in a module bay (or devices in a device bay). For example, the EX4100-48P comes preinstalled with two fan modules and one 920w power supply. When deploying many (or even just a handful) of these devices in Netbox, it seems like quite a burden to have to create and install all of the fan modules and power supplies. I suppose the device import can accomplish this, but I've not used it yet.

2023-04-26 13:34 UTC, danner26 commented
Hello, currently there is no way to pre-define the installation of modules. You can automate that using something like ansible, the API or doing bulk imports, but otherwise there is not currently a way.

The API and subsequent programatic methods of interacting with NetBox will be your best friend when importing a lot of data into the system

2023-04-26 13:38 UTC, danner26 requested changes

2023-04-26 13:38 UTC, danner26 commented on device-types/Juniper/EX4100-48T.yaml
> +slug: ex4100-48t
Slugs should have the manufacturer appended to them. For this instance, `juniper-`

2023-04-26 13:38 UTC, danner26 commented on device-types/Juniper/EX4100-48T.yaml
> +u_height: 1
Please add the following missing values, if you have them:

1. `part_number`
2. `is_full_depth`
3. `airflow`
4. `weight` and `weight_unit`

If you do not have, or cannot find any of these values just let me know. Often you canfind all of these on the manufacturers datasheet for this product

2023-04-26 13:38 UTC, danner26 commented on device-types/Juniper/EX4100-48P.yaml
> +u_height: 1
Please add the following missing values, if you have them:

1. `part_number`
2. `is_full_depth`
3. `airflow`
4. `weight` and `weight_unit`

If you do not have, or cannot find any of these values just let me know. Often you canfind all of these on the manufacturers datasheet for this product

2023-04-26 13:38 UTC, danner26 commented on device-types/Juniper/EX4100-24T.yaml
> +u_height: 1
Please add the following missing values, if you have them:

1. `part_number`
2. `is_full_depth`
3. `airflow`
4. `weight` and `weight_unit`

If you do not have, or cannot find any of these values just let me know. Often you canfind all of these on the manufacturers datasheet for this product

2023-04-26 13:38 UTC, danner26 commented on device-types/Juniper/EX4100-24P.yaml
> +u_height: 1
Please add the following missing values, if you have them:

1. `part_number`
2. `is_full_depth`
3. `airflow`
4. `weight` and `weight_unit`

If you do not have, or cannot find any of these values just let me know. Often you canfind all of these on the manufacturers datasheet for this product

2023-04-26 15:49 UTC, danner26 approved these changes

2023-04-26 15:49 UTC, merged