Add SR850.yaml
netbox-community/devicetype-library pull request #1316
Opened 2023-04-26 19:42 UTC by muratbulat

Reference: https://lenovopress.lenovo.com/lp1052.pdf

2023-04-30 01:46 UTC, muratbulat reviewed
ThinkSystem SR850

2023-04-30 01:48 UTC, muratbulat reviewed
lower

2023-05-08 14:51 UTC, danner26 requested changes

2023-05-08 14:51 UTC, danner26 commented on device-types/Lenovo/SR850.yaml
> +power-ports:
According to the datasheet, the PSUs are hot-swappable. So the power slots should be created in `module-bays`, and then the associated PSU's themselves should be added to the module-types folder if they do not already exist

2023-05-08 14:51 UTC, danner26 commented on device-types/Lenovo/SR850.yaml
> +  - name: XCC
Is there only one interface on this device?

2023-05-08 14:51 UTC, danner26 commented on device-types/Lenovo/SR850.yaml
> +subdevice_role: parent
`subdevice_role: parent` should only be used when there are children devices, which would be housed under `device-bays`

An example of this is the Dell VRTX chassis. The chassis itself is a device, which is a parent to blades such as the M620.

Unless this device houses other devices, which I cannot find information saying it does, then please remove this definition.

2023-05-08 14:51 UTC, danner26 commented on device-types/Lenovo/SR850.yaml
> +slug: sr850
The slug for this should be `lenovo-thinksystem-sr850`

2023-05-08 14:51 UTC, danner26 commented on device-types/Lenovo/SR850.yaml
> +comments: '[Lenovo System SR850 product guide](https://lenovopress.lenovo.com/lp1052.pdf)'
Please add `weight` and `airflow` definitions

2023-05-08 14:51 UTC, danner26 commented on device-types/Lenovo/SR850.yaml
> +part_number: 7B27A03953
This part number appears to only be for the processor and memory expansion tray. This is not the part number for the device itself.

2023-05-13 06:48 UTC, closed without merging