Add FS S5800-24T16B switch
netbox-community/devicetype-library pull request #1325
Opened 2023-05-04 19:54 UTC by BarbarossaTM

2023-05-05 17:18 UTC, BarbarossaTM commented
Thanks for fixing the checks :-)

2023-05-08 14:01 UTC, danner26 requested changes

2023-05-08 14:18 UTC, BarbarossaTM commented on device-types/FS/S5800-24T16B.yaml
> +  - name: psu1
Aye, will do

2023-05-12 18:47 UTC, danner26 commented on device-types/FS/S5800-24T16B.yaml
> +  - name: eth0-1
Then the configuration should reflect that, the name of the interface should be `eth-0-1` rather than `eth0-1`

2023-05-12 19:48 UTC, BarbarossaTM commented on device-types/FS/S5800-24T16B.yaml
> +  - name: eth0-1
Shoot, you're right, fixed!

2023-05-22 14:50 UTC, danner26 requested changes
A few final changes, please review and let me know if you have any questions

2023-05-22 14:50 UTC, danner26 commented on device-types/FS/S5800-24T16B.yaml
> +slug: s5850-24t16b
Please append the manufacturers name to the slug, like so: `fs-`

2023-05-22 14:50 UTC, danner26 commented on device-types/FS/S5800-24T16B.yaml
> +airflow: front-to-rear
Please add `weight` and `weight_unit` information if you can find it

2023-06-29 04:01 UTC, closed without merging