Add Cisco MR74 and Fix MR36 File Name
netbox-community/devicetype-library pull request #1366
Opened 2023-05-18 08:17 UTC by stuntguy3000

As per title.

2023-05-18 12:42 UTC, danner26 requested changes

2023-05-18 12:42 UTC, danner26 commented on device-types/Cisco/Meraki-MR74.yaml
> +is_full_depth: false
Please add `weight` and `weight_unit` if you can

2023-05-18 12:43 UTC, danner26 commented
Also the build is failing because you are missing a newline at the end of the MR74 file

2023-05-22 02:23 UTC, stuntguy3000 commented
Fixed.

2023-05-22 13:49 UTC, merged