Adding equipment from the manufacturer DATACOM
netbox-community/devicetype-library pull request #1391
Opened 2023-05-25 18:44 UTC by rogeriomendesp

2023-05-25 22:20 UTC, rogeriomendesp commented
![image](https://github.com/netbox-community/devicetype-library/assets/57509385/5c29d114-0577-4b09-b860-948b6009d752)


Hi,

I've tried everything, I can't succeed.

any suggestion?

Thanks.

2023-05-26 12:53 UTC, rogeriomendesp commented
![image](https://github.com/netbox-community/devicetype-library/assets/57509385/e9950b2f-e437-4450-aabd-8ee5c9a28959)

2023-06-30 19:24 UTC, rogeriomendesp commented
Hi,

I've tried everything, I can't succeed.

any suggestion?

Thanks.

2023-06-30 19:28 UTC, rogeriomendesp reviewed
Update

2023-07-03 18:02 UTC, ivareri commented
@rogeriomendesp Seems like yamlfmt removes the `'` thats around the part_number, and splits the `comments:` into two lines. 

Try running `pre-commit run --files device-types/Datacom/DM4050-24GT-6XS.yaml`, followed by `git diff`.  Should show you the changes, if it looks OK you could just try to `git add` the file again and re-run the pre-commit check

2023-07-03 19:30 UTC, rogeriomendesp commented
> pre-commit run --files device-types/Datacom/DM4050-24GT-6XS.yaml

![image](https://github.com/netbox-community/devicetype-library/assets/57509385/d301a05b-f42c-498f-9b6c-41442255754b)

2023-07-04 11:27 UTC, ivareri commented
Did you follow the chapter on [Data Validation](https://github.com/netbox-community/devicetype-library#data-validation--commit-quality-checks) in the readme? 

Then something like this:

![Screenshot](https://github.com/netbox-community/devicetype-library/assets/1616486/abea04a6-deb1-45a1-8f01-508b9c3c18ec)

2023-07-04 11:34 UTC, ivareri commented on device-types/Datacom/DM4050-24GT-6XS.yaml
> +  1U Metal cabinet for 19-inch racks. Two slots for power supplies Power supplies and SFPs to be ordered separately (https://www.datacom.com.br/uploads/product/file/97aede61eba553f23060d983b6e68152.p
Seems like this is the change yamlfmt wants

```suggestion
comments: L2/L3 wirespeed switch with 24 electrical Gigabit Ethernet ports (RJ45SFP) and 6 optical 10Gisgabit Ethernet ports (SFP+) 1U Metal cabinet for
  19-inch racks. Two slots for power supplies Power supplies and SFPs to be ordered separately (https://www.datacom.com.br/uploads/product/file/97aede61eba553f23060d983b6e68152.pdf)

2023-07-04 13:03 UTC, rogeriomendesp commented
> Você seguiu o capítulo sobre [validação de dados](https://github.com/netbox-community/devicetype-library#data-validation--commit-quality-checks) no leia-me?
> 
> Então algo assim:
> 
> ![Captura de tela](https://user-images.githubusercontent.com/1616486/250887826-abea04a6-deb1-45a1-8f01-508b9c3c18ec.png)

sorry.

I do it through github desktop.

2023-07-04 13:11 UTC, rogeriomendesp commented
Hi,
Is there a way to pre-commit on github desktop?

Thanks.

2023-07-04 15:21 UTC, jsenecal commented
> Hi, Is there a way to pre-commit on github desktop?

You also need a python environment to run the scripts, etc.
Know anything about vscode and wsl2 ?

Perhaps someone else can pick up where you left off and properly lint your files :)

2023-07-07 12:26 UTC, rogeriomendesp commented
Hi

I'm changing the files, I'll pre-commit and then send them.

2023-07-12 13:59 UTC, danner26 requested changes

2023-07-12 13:59 UTC, danner26 commented on device-types/Datacom/DM4050-24GT-6XS.yaml
> +slug: dm4050-24gt-6xs
Please append `datacom-` to the slug name

2023-07-12 13:59 UTC, danner26 commented on device-types/Datacom/DM4050-24GT-6XS.yaml
> +    type: usb-mini-b
Is this console port actually used for console access? If not, please remove it.

2023-07-14 20:02 UTC, danner26 commented
Hello, we have released a new set of tests and features to assist with properly creating definition files for the DeviceType-Library. These tests will ensure that all files conform to a standardized format and contain valid data. Over the coming weeks we will be adding more tests to handle other currently undefined cases. If you notice anything that you believe is a bug, please @ me in a comment and details what you think is incorrect.

Along with additional test cases we have added a feature that will annotate why tests fail. To access these annotations after a test has completed, please navigate to the _Files changed_ tab within your PR. At the very bottom of the page you will see a list of errors along with the filename in question and the error which was found.

With all this being said, if your PR is validated then great! Please @ me me so I can review it further! If your PR is not valid, please review the issues and correct them; in the meantime I will mark your PR as a draft. After correcting the issues and recieving a valid status, please mark the PR as ready to be reviewed. Thank you!

2023-07-25 15:35 UTC, danner26 commented
Hey, thanks for reaching out. The first issue is that you are working directly on the master branch. I would suggest that you copy your changed files elsewhere, say to /tmp and then pull down the latest changes into your GitHub fork. Once that is done, do a `git fetch` and reset your master branch to the head commit (which should be the latest master commit on the upstream repo). After restoring the master branch, create a new branch off of the master. `git checkout -b <branch_name>`. Replace `<branch_name>` with the name youd like to call your branch. Then add your files back, commit and run the tests.

That should help resolve a lot of your issues  you are facing

2023-07-26 13:23 UTC, closed without merging