Add Cisco ISR 1127-8PLTEP & Cisco LTE Modules
netbox-community/devicetype-library pull request #1406
Opened 2023-05-31 05:41 UTC by stuntguy3000

This change adds a Cisco ISR router with a selection of LTE modules available.

2023-07-08 04:09 UTC, stuntguy3000 commented
Re-opening requesting merge.

2023-07-08 04:10 UTC, stuntguy3000 commented
@danner26 fyi

2023-07-12 13:24 UTC, danner26 commented
Hey @stuntguy3000 sorry I have been backed up. I have reopened this

2023-07-12 13:25 UTC, stuntguy3000 commented
No worries mate, let me know if you need any changes

2023-07-12 13:35 UTC, jsenecal requested changes
Looks good to me, please address the few items I noted.

2023-07-12 13:35 UTC, jsenecal commented on device-types/Cisco/ISR-1127-8PLTEP.yaml
> +    position: '1'
Is this "1" really useful here ? There is only one slot. Is there another ISR model with multiple slots ? 
Usually this identifier is used in module-types as part of their name or components using templated strings like such: ge-0/{module}/0

2023-07-12 13:53 UTC, danner26 requested changes

2023-07-12 13:53 UTC, danner26 commented on device-types/Cisco/ISR-1127-8PLTEP.yaml
> +is_full_depth: false
Please add `airflow: passive` since these are fanless devices

2023-07-12 13:53 UTC, danner26 commented on device-types/Cisco/ISR-1127-8PLTEP.yaml
> +u_height: 1
I do not believe this is a racked device. It looks like by default this is a desktop/shelf device. If this is true please modify this to `u_height: 0`

2023-07-12 13:53 UTC, danner26 commented on device-types/Cisco/ISR-1127-8PLTEP.yaml
> +    type: usb-micro-b
Is this port actually used for console access? If so then this is fine, if not then please remove it.

2023-07-12 13:53 UTC, danner26 commented on device-types/Cisco/ISR-1127-8PLTEP.yaml
> +    type: iec-60320-c14
Unless I am looking at the wrong device, which I do not believe I am, this should be a `dc-terminal` not a c14

2023-07-14 20:02 UTC, danner26 commented
Hello, we have released a new set of tests and features to assist with properly creating definition files for the DeviceType-Library. These tests will ensure that all files conform to a standardized format and contain valid data. Over the coming weeks we will be adding more tests to handle other currently undefined cases. If you notice anything that you believe is a bug, please @ me in a comment and details what you think is incorrect.

Along with additional test cases we have added a feature that will annotate why tests fail. To access these annotations after a test has completed, please navigate to the _Files changed_ tab within your PR. At the very bottom of the page you will see a list of errors along with the filename in question and the error which was found.

With all this being said, if your PR is validated then great! Please @ me me so I can review it further! If your PR is not valid, please review the issues and correct them; in the meantime I will mark your PR as a draft. After correcting the issues and recieving a valid status, please mark the PR as ready to be reviewed. Thank you!

2023-07-15 12:37 UTC, stuntguy3000 commented
Comments addressed, back to you guys!

Nice work on those tests, caught some errors.

2023-07-17 19:42 UTC, danner26 approved these changes

2023-07-17 19:46 UTC, merged