Add Cisco UCS-C220-M6S
netbox-community/devicetype-library pull request #1432
Opened 2023-06-19 13:17 UTC by btriller

Add Cisco UCS-C220-M6S device and various Cisco PSU module types.

2023-06-19 20:04 UTC, DanSheps requested changes
Please try and include weights on all items if at all possible.

2023-06-19 20:04 UTC, DanSheps commented on device-types/Cisco/UCSC-C220-M6S.yaml
> +  - name: ens1f0
These are how the names present in Linux.

IMO, I would name them how they would present in a managed (fabric interconnect connected) environment instead or a generic "Ethernet 1, Ethernet 2"

2023-06-19 20:04 UTC, DanSheps commented on device-types/Cisco/UCSC-C220-M6S.yaml
> +    position: '2'
> 3 PCIe 4.0 slots plus 1 dedicated 12-Gbps RAID controller slot and 1 dedicated mLOM slot

I would include these slots, as they could house an additional network adapter.

2023-07-14 20:01 UTC, danner26 commented
Hello, we have released a new set of tests and features to assist with properly creating definition files for the DeviceType-Library. These tests will ensure that all files conform to a standardized format and contain valid data. Over the coming weeks we will be adding more tests to handle other currently undefined cases. If you notice anything that you believe is a bug, please @ me in a comment and details what you think is incorrect.

Along with additional test cases we have added a feature that will annotate why tests fail. To access these annotations after a test has completed, please navigate to the _Files changed_ tab within your PR. At the very bottom of the page you will see a list of errors along with the filename in question and the error which was found.

With all this being said, if your PR is validated then great! Please @ me me so I can review it further! If your PR is not valid, please review the issues and correct them; in the meantime I will mark your PR as a draft. After correcting the issues and recieving a valid status, please mark the PR as ready to be reviewed. Thank you!

2023-07-17 19:39 UTC, merged