Create MES5324.yml
netbox-community/devicetype-library pull request #1594
Opened 2023-08-30 14:44 UTC by GitRost

Fix Mgmt interfice

2023-09-06 15:05 UTC, danner26 requested changes

2023-09-06 15:05 UTC, danner26 commented on device-types/Eltex/MES5324.yml
> +is_full_depth: false
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2023-09-06 15:05 UTC, danner26 commented on device-types/Eltex/MES5324.yml
> +    maximum_draw: 107
It appears that the PSUs on this device are modular. If that is the case, then you should be modelling these under `module-bays` and the applicable modular PSUs should be added under the module-types folder

2023-10-06 17:23 UTC, danner26 commented
Did you just ignore both of my comments and request a re-review?

2023-10-13 06:45 UTC, GitRost commented
> Did you just ignore both of my comments and request a re-review?

Sorry if I inserted something in the wrong place and clicked the wrong thing.
I don’t know how to use github, and nothing is intuitive here.

2023-10-13 06:55 UTC, closed without merging