adding LC 96 fiber patch panel
netbox-community/devicetype-library pull request #1613
Opened 2023-09-07 13:18 UTC by dejantep

2023-09-07 13:31 UTC, DanSheps requested changes
Is this simplex 96 or duplex 96?  Seems like a lot of ports.

Also, is it actually generic or is there a specific manufacturer and you are just genericising it?

2023-09-07 13:31 UTC, DanSheps commented on tests/known-modules.pickle
Pretty sure we don't want the pickle files included

2023-09-07 13:31 UTC, DanSheps commented on tests/known-slugs.pickle
Same as above

2023-09-07 13:33 UTC, dejantep commented on tests/known-modules.pickle
true but i'm not sure what i'm doing wrong

2023-09-07 13:36 UTC, dejantep commented on tests/known-modules.pickle
its generic and every port has its own number 1-96 so simplex is possible
its known as LC quad something....

2023-09-07 13:37 UTC, dejantep commented on tests/known-modules.pickle
![image](https://github.com/netbox-community/devicetype-library/assets/71568639/650aff1f-a1d6-4a94-baeb-7dcece13f2b8)

2023-09-07 13:56 UTC, dejantep reviewed
ok. remove the files

2023-09-07 14:01 UTC, DanSheps approved these changes
Looks good from my end, but I only took a quick look.  I will let @danner26 do a more in-depth dive.  😄

2023-10-31 17:06 UTC, dejantep commented
is there anything i can do to help to merge this?

2023-11-20 17:57 UTC, danner26 commented
Please remove the pickle files from your PR. These should not be included at any time

2023-11-21 21:55 UTC, closed without merging