Adds ProCurve 1810-24G model
netbox-community/devicetype-library pull request #1651
Opened 2023-10-02 13:09 UTC by hooligan-sa

2023-10-06 17:26 UTC, danner26 requested changes

2023-10-06 17:26 UTC, danner26 commented on device-types/HPE/ProCurve-1810-24G.yaml
> +is_full_depth: false
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2023-11-09 06:09 UTC, hooligan-sa commented
Fo some reason I can't see what changes you want - Please advise @danner26

2023-11-09 06:10 UTC, hooligan-sa reviewed
I believe all changes are complete

2023-11-20 17:52 UTC, danner26 approved these changes

2023-11-20 17:52 UTC, merged