Cisco access points
netbox-community/devicetype-library pull request #1673
Opened 2023-10-12 13:13 UTC by francesco-noc

I don't know why this time i had to add the .pre-commit-config.yaml file.
I had this error when I tryed to commit:
[ERROR] Your pre-commit configuration is unstaged.
`git add .pre-commit-config.yaml` to fix this.

2023-11-20 18:13 UTC, danner26 commented
The `weight` and `weight_unit` definitions should be available in the product datasheet. Can you please add those? Also add `airflow` if you can find if it is passive or directional. Thank you

2023-11-29 10:52 UTC, francesco-noc commented
> @francesco-noc Is this ready for review again?

Yes.

2023-12-20 16:58 UTC, DanSheps requested changes

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/AIR-AP1815I-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/AIR-CAP2702E-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/AIR-CAP1702I-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/AIR-AP2802I-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/AIR-AP1832I-E-K9C.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/AIR-AP1832I-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/AIR-CAP2702I-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3702I-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3702I-E-K9.yaml
> +    type: ieee802.11ac
Missing console definition

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/C9105AXI-E.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/C9105AXI-E.yaml
> +model: Catalyst 9105AXI-E
Should include all variants of the 9105AXI (-A, -B, -H, -Q, -K, -T, -G, -D, -S, -I, -Z, -F, -N, -C, -R) if we are specifying the "-E".

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/C9115AXI-E.yaml
> +model: Catalyst 9115AXI-E
Should include all variants of the 9115AXI (-A, -B, -H, -Q, -K, -T, -G, -D, -S, -I, -Z, -F, -N, -C, -R) if we are specifying the "-E".

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/C9120AXE-E.yaml
> +model: Catalyst 9120AXE-E
Should include all variants of the 9120AXE (-A, -B, -H, -Q, -K, -T, -G, -D, -S, -I, -Z, -F, -N, -C, -R) if we are specifying the "-E".

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/C9124AXE-E.yaml
> +model: Catalyst 9124AXE-E
Should include all variants of the 9124AXE (-A, -B, -H, -Q, -K, -T, -G, -D, -S, -I, -Z, -F, -N, -C, -R) if we are specifying the "-E".

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/C9115AXI-E.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/C9120AXE-E.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:58 UTC, DanSheps commented on device-types/Cisco/C9124AXE-E.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2024-02-05 12:59 UTC, francesco-noc commented
Changes made!

2024-02-15 20:55 UTC, DanSheps approved these changes

2024-04-03 13:44 UTC, danner26 commented
@francesco-noc please resolve the conflicts or close this PR, thank you.

2024-04-03 13:50 UTC, francesco-noc commented
Sorry, I can work on it (and on other PRs) tomorrow.

2024-05-23 08:46 UTC, closed without merging