Add Cisco C891-K9
netbox-community/devicetype-library pull request #1721
Opened 2023-10-27 14:45 UTC by buddhainkovy

Add Cisco C891-K9

2023-10-27 14:56 UTC, buddhainkovy commented
Add Cisco C891-K9

2023-10-27 15:15 UTC, buddhainkovy commented
Add Cisco C891-K9

2023-10-31 15:42 UTC, DanSheps requested changes

2023-10-31 15:42 UTC, DanSheps commented on device-types/Cisco/C891-K9.yaml
> +is_full_depth: false
The weight is available, please include the weight

2023-12-28 04:01 UTC, closed without merging