Create RS822RP+.yaml
netbox-community/devicetype-library pull request #1755
Opened 2023-11-09 10:43 UTC by pierrickj

2023-11-09 10:46 UTC, pierrickj commented
Add Synology RS822RP+ NAS Model

2023-11-20 16:09 UTC, danner26 requested changes

2023-11-20 16:09 UTC, danner26 commented on device-types/Synology/RS822RP+.yaml
> +    label: PSU 2
The power for this chassis appears to be modular, is that correct?
If so, you should create `module-bays` on this device and then add the associated PSU definitions to the module-types folder

2023-11-20 16:09 UTC, danner26 commented on device-types/Synology/RS822RP+.yaml
> +is_full_depth: true
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2023-12-28 04:01 UTC, closed without merging