Poweredge r750xs
netbox-community/devicetype-library pull request #1769
Opened 2023-11-17 07:38 UTC by max0013

2023-11-17 16:18 UTC, danner26 commented
Why do you have two different models, one with esxi? The purpose of this library is for the physical devices themselves. Please ensure you do not have redundant devices in a PR

2023-11-22 07:31 UTC, max0013 commented
oh yeah, it was for testing something, its presence in the commit is a mistake sorry. 
I just delete it

2023-11-30 16:10 UTC, danner26 requested changes

2023-11-30 16:10 UTC, danner26 commented on device-types/Dell/PowerEdge-R750xs.yml
> +rear_image: true
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2023-11-30 16:10 UTC, danner26 commented on device-types/Dell/PowerEdge-R750xs.yml
> +    type: other
Video and USBs are not suppose to be modelled here. Please remove these

2023-11-30 16:10 UTC, danner26 commented on device-types/Dell/PowerEdge-R750xs.yml
> +    type: other
If this refers to the iDRAC serial port, please model this under `console-ports` with the proper interface type

2023-11-30 16:10 UTC, danner26 commented on device-types/Dell/PowerEdge-R750xs.yml
> +    rear_port: Rear USB 2
Video and USBs are not suppose to be modelled in NetBox at the moment. Please remove them

2023-11-30 16:10 UTC, danner26 commented on device-types/Dell/PowerEdge-R750xs.yml
> +    rear_port: iDrac
This should be modelled under the `console-ports` section with the proper interface type

2023-11-30 16:10 UTC, danner26 commented on device-types/Dell/PowerEdge-R750xs.yml
> +    type: iec-60320-c14
These PSUs are modular. You should be modelling this as `module-bays`, and the associated PSU modules should be created in the module-types folder if they do not already exist

2023-11-30 16:10 UTC, danner26 commented on device-types/Dell/PowerEdge-R750xs.yml
> +    position: Integrated.1:RAID.Slot.1-1
Currently storage is not suppose to be modelled in NetBox. We have an open FR to work on that, but it is not currently ready. Please remove these definitions.

2023-11-30 16:10 UTC, danner26 commented on device-types/Dell/PowerEdge-R750xs.yml
> +    label: DDR4 DIMM
Unfortunately these should not be modelled in NetBox at this time. Please remove them.

2024-01-08 04:01 UTC, closed without merging