Add Cisco Aironet wireless access points
netbox-community/devicetype-library pull request #1783
Opened 2023-11-27 18:55 UTC by abu-rehan

This pull request adds a number of cisco access points. They are from different series and so I have simply named the branch as aironet-access-points. This is my first contribution and so, I may be off on something. Please let me know of any edits I have to make.

2023-12-20 16:35 UTC, DanSheps requested changes

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-AP1121G-E-K9.yaml
> +  - name: WAN
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-AP1121G-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-LAP1242N-E-K9.yaml
> +  - name: WAN
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-LAP1242N-C-K9.yaml
> +  - name: WAN
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-LAP1242N-A-K9.yaml
> +  - name: WAN
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3702I-Z-K9.yaml
> +  - name: WAN
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3702E-E-K9.yaml
> +  - name: WAN
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3602I-T-K9.yaml
> +  - name: Port 1
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3602I-S-K9.yaml
> +  - name: Port 1
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3602I-K-K9.yaml
> +  - name: Port 1
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3602I-C-K9.yaml
> +  - name: Port 1
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3602E-E-K9.yaml
> +  - name: Port 1
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3502I-E-K9.yaml
> +  - name: Port 1
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3502E-E-K9.yaml
> +  - name: Port 1
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP2602I-E-K9.yaml
> +  - name: Port 1
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP1552SA-E-K9.yaml
> +  - name: Port 1
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP1552H-E-K9.yaml
> +  - name: Port 1
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-AP3802I-Z-K9.yaml
> +  - name: WAN
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-AP3802I-T-K9.yaml
> +  - name: WAN
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-AP3802I-E-K9.yaml
> +  - name: WAN
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-AP3802E-E-K9.yaml
> +  - name: WAN
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-AP1562E-B-K9.yaml
> +  - name: WAN
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-AP1562E-B-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-AP3802E-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-AP3802I-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-AP3802I-T-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-AP3802I-Z-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP1552H-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP1552SA-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP2602E-E-K9.yaml
> +  - name: Port 1
Physically this is "Ethernet", Logically, it is generally "GigabitEthernet0"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP2602E-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP2602I-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3502E-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3502I-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3602E-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3602I-C-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3602I-K-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3602I-S-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3602I-T-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3702E-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-CAP3702I-Z-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-LAP1242N-A-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-LAP1242N-C-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2023-12-20 16:35 UTC, DanSheps commented on device-types/Cisco/AIR-LAP1242N-E-K9.yaml
> +  - name: WiFi
Should be "Dot11Radio0"

There should also be a "Dot11Radio1"

2024-01-04 20:25 UTC, abu-rehan commented on device-types/Cisco/AIR-AP1121G-E-K9.yaml
> +    type: 100base-tx
@DanSheps Do you mean this?
```suggestion
    type: ethernet
```

2024-02-12 04:01 UTC, closed without merging