add some cisco device types of different series
netbox-community/devicetype-library pull request #1811
Opened 2023-12-15 16:23 UTC by abu-rehan

Hi! I used existing schemas as reference. I believe I have put in all the mandatory info. Some optional info may be missing but would still like this PR to get accepted if possible... :-)

2024-01-04 20:19 UTC, danner26 requested changes

2024-01-04 20:19 UTC, danner26 commented on device-types/Cisco/C9300L-24UXG-4X.yaml
> +is_full_depth: true
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-01-04 20:19 UTC, danner26 commented on device-types/Cisco/WS-C3550-48-SMI.yaml
> +u_height: 1
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-01-04 20:19 UTC, danner26 commented on device-types/Cisco/WS-C3560G-24TS-E.yaml
> +u_height: 1
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-01-04 20:19 UTC, danner26 commented on device-types/Cisco/WS-C3560G-24TS-S.yaml
> +u_height: 1
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-01-04 20:19 UTC, danner26 commented on device-types/Cisco/WS-C3560G-48PS-E.yaml
> +u_height: 1
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-02-08 17:02 UTC, DanSheps approved these changes
These are all Catalyst switches so the weight and airflow is easy to find on the datasheet.  Please add them and we can get this merged in.

2024-02-16 04:01 UTC, closed without merging