Generic sc and st fiber patch panels
netbox-community/devicetype-library pull request #1817
Opened 2023-12-19 15:49 UTC by jhofmueller

Adding three generic fiber patch panels:

* 24 port st
* 16 port st
* 12 port sc duplex

All with one splice rear port.

2024-01-04 20:07 UTC, danner26 commented
I am by far not an expert on these, @DanSheps any comments?

2024-01-04 20:12 UTC, DanSheps commented
TBH, I don't know if this makes sense.

If it is a panel, you generally wouldn't have a splice.  This seems to far out there to be "generic" and is likely tied to a specific product.

2024-01-04 20:25 UTC, danner26 commented
@DanSheps kind of this [this PR](https://github.com/netbox-community/devicetype-library/pull/1807) they raised?

2024-01-04 21:15 UTC, DanSheps commented
I don't know, honestly it is my view that these should all have individual rear ports for each front port since it is an individual splice and an individual strand.

Now this is just my view, but I think it is the most technically correct view when modelling any kind of fibre plant.

2024-01-22 16:04 UTC, danner26 commented
@DanSheps care to re-review this?

2024-01-23 05:04 UTC, DanSheps requested changes
Sorry, I thought I responded to this for some reason.

2024-01-23 05:04 UTC, DanSheps commented on device-types/Generic/SC-12-port-duplex-fiber-patch-panel-rear-splice.yaml
This file still has a multiple position rear port.  Is this intended?

2024-01-23 08:12 UTC, jhofmueller commented on device-types/Generic/SC-12-port-duplex-fiber-patch-panel-rear-splice.yaml
No, this was not intended. Fixed it.

2024-01-23 18:43 UTC, DanSheps commented on device-types/Generic/SC-12-port-duplex-fiber-patch-panel-rear-splice.yaml
Mark it ready for review when you are ready.

2024-01-25 14:17 UTC, DanSheps approved these changes

2024-02-26 08:28 UTC, jhofmueller commented on device-types/Generic/SC-12-port-duplex-fiber-patch-panel-rear-splice.yaml
How would I do that? It's not a draft anymore, issues have been resolved and approved by you. Please advise.

2024-03-01 15:57 UTC, merged