Added additional cisco device types
netbox-community/devicetype-library pull request #1836
Opened 2023-12-21 16:57 UTC by abhi1693

2023-12-21 19:39 UTC, DanSheps requested changes
Might need weights.

The 9500-16X-A should only be a 9500-16X which might already be in the database.  The "-A" is just a ordering SKU

2023-12-21 19:39 UTC, DanSheps commented on device-types/Cisco/WS-C3850-12X48U-S.yaml
> +part_number: WS-C3850-12X48U-S
So funny enough, the 3850 actually makes this distinction in inventory, even though the device itself is soft-upgradeable to a higher license level I believe.

```
NAME: "Switch 1", DESCR: "WS-C3850-48F-L"
PID: WS-C3850-48F-L    , VID: V07  , SN: <REDACTED>
```

2023-12-21 19:39 UTC, DanSheps commented on device-types/Cisco/C9500-16X-A.yaml
> +part_number: C9500-16X-A
"-A" is just a license identifier for ordering.  The actual model number is C9500-16X.

AP's are different with the "-A" or "-I", etc as those are regional locks and the AP actually reports the specific model number for the region.

```
NAME: "Switch 1", DESCR: "C9500-16X"
PID: C9500-16X         , VID: V02  , SN:  <REDACTED>
```

2023-12-22 10:55 UTC, abhi1693 commented
While I was adding the weights for the ones I submitted, I took the liberty to add the missing ones in the existing data as well.

2024-01-04 19:07 UTC, danner26 requested changes

2024-01-04 19:07 UTC, danner26 commented on device-types/Cisco/Meraki-MS225-24.yaml
> +weight_unit: lb
2. Please add the `airflow` data point if you have it or can find it. This appears to be in the datasheet (passive)

2024-02-08 08:25 UTC, lucatortiglione commented
is there a way to fix the missing info by myself and close the pull ?

2024-04-03 13:46 UTC, danner26 commented
@lucatortiglione you can create a fork of this PR and then submit a new PR (and reference this one please). Otherwise no, unless he gives you access to his fork

2024-04-03 13:46 UTC, danner26 commented
@abhi1693 can you please let us know if you are going to work on this, and if not can you close it?

2024-08-22 16:17 UTC, danner26 commented
Closing this since it has been incomplete for a long period of time. Feel free to work on it then reopen it again if you would like.

2024-08-22 16:17 UTC, closed without merging