Added some Netgear M4300 models
netbox-community/devicetype-library pull request #1860
Opened 2024-01-16 16:56 UTC by tlourey

Hi, 

I have added the following Netgear devices and modules: 

- Netgear M4300-52G-PoE+
- Netgear M4300-28G-PoE+
- Netgear APS550W PSU Module

Assuming tests pass, please review. Thanks.

2024-02-14 13:30 UTC, tlourey commented
Hi Team, can someone review? Many thanks. Tim

2024-03-22 19:05 UTC, danner26 requested changes

2024-03-22 19:05 UTC, danner26 commented on device-types/Netgear/M4300-28G-PoEp.yaml
> +  - name: 1/0/
Looks like this name might me missing the ending number.

2024-03-22 19:05 UTC, danner26 commented on device-types/Netgear/M4300-28G-PoEp.yaml
> +    mgmt_only: false
This definition should be removed, we are really only focusing on physical definitions in the devicetype-library

2024-03-22 19:05 UTC, danner26 commented on device-types/Netgear/M4300-52G-PoEp.yaml
> +subdevice_role: parent
This should be removed, you should only use `subdevice_role` if other devices slot into this one, i.e. `device-bays`

`module-bays` do not count as children

2024-03-22 19:05 UTC, danner26 commented on device-types/Netgear/M4300-28G-PoEp.yaml
> +subdevice_role: parent
This should be removed, you should only use `subdevice_role` if other devices slot into this one, i.e. `device-bays`

`module-bays` do not count as children

2024-03-22 19:05 UTC, danner26 commented on device-types/Netgear/M4300-52G-PoEp.yaml
> +    mgmt_only: false
This definition should be removed, we are really only focusing on physical definitions in the devicetype-library

2024-04-03 13:48 UTC, danner26 commented
Hello @tlourey can you please resolve the issues, or close this PR? Thank you.

2024-04-04 00:40 UTC, tlourey commented
Will do. I'm away right now but should be able to next week.

On Thu, 4 Apr 2024, 12:49 am Daniel W. Anner, ***@***.***>
wrote:

> Hello @tlourey <https://github.com/tlourey> can you please resolve the
> issues, or close this PR? Thank you.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/netbox-community/devicetype-library/pull/1860#issuecomment-2034667503>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACH7VA2DRO5ZIKIEKWX27NDY3QCGJAVCNFSM6AAAAABB5EQKJ2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMZUGY3DONJQGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-22 16:17 UTC, closed without merging

2024-08-22 16:18 UTC, danner26 commented
Closing this since it has been incomplete for a long period of time. Feel free to work on it then reopen it again if you would like.