Cisco devices
netbox-community/devicetype-library pull request #1878
Opened 2024-01-23 14:37 UTC by francesco-noc

2024-01-23 15:08 UTC, francesco-noc commented
Sorry I clicked by mistake. 
I'm still having problems with the pickle files.

2024-01-23 15:10 UTC, danner26 commented
Hey, you can try grabbing the latest pickle files and adding those, that might solve the issue. If not starting a new branch with the changes will definitely fix it.

I am actively merging things so there is a chance the first options does not work

2024-01-25 15:52 UTC, DanSheps requested changes

2024-01-25 15:52 UTC, DanSheps commented on device-types/Cisco/C9500-24Y4C-A.yaml
> +    maximum_draw: 650
Power ports should be modules for this model

2024-01-25 15:52 UTC, DanSheps commented on device-types/Cisco/C9120AXI-E.yaml
> +
I don't think we need a line break here

2024-01-25 15:52 UTC, DanSheps commented on device-types/Cisco/C9120AXI-E.yaml
> +
I don't think we need a line break here

2024-01-25 15:52 UTC, DanSheps commented on device-types/Cisco/IE-2000-4TS-G-L.yaml
Please add weight

2024-01-25 15:52 UTC, DanSheps commented on device-types/Cisco/IE-2000-16PTC-G-L.yaml
Please add weight

2024-01-25 15:52 UTC, DanSheps commented on device-types/Cisco/IE-3000-4TC.yaml
Please add weight

2024-01-25 15:52 UTC, DanSheps commented on device-types/Cisco/N7K-C7009.yaml
> +    type: rj-45
This should be part of the supervisor module

2024-01-25 15:52 UTC, DanSheps commented on device-types/Cisco/N7K-C7009.yaml
Please add weight

2024-01-25 15:52 UTC, DanSheps commented on device-types/Cisco/WS-C3560-24PS-S.yaml
Please add weight

2024-01-25 15:52 UTC, DanSheps commented on device-types/Cisco/WS-C3560G-24PS-S.yaml
Please add weight

2024-01-25 15:52 UTC, DanSheps commented on device-types/Cisco/WS-C3560G-24TS-S.yaml
Please add weight

2024-01-25 15:52 UTC, DanSheps commented on device-types/Cisco/WS-C3750X-24S-E.yaml
Please add weight

2024-01-25 15:52 UTC, DanSheps commented on device-types/Cisco/WS-C3850-24S-E.yaml
Please add weight

2024-01-26 10:17 UTC, francesco-noc commented
changes made!

2024-03-22 14:40 UTC, DanSheps approved these changes

2024-03-22 14:40 UTC, DanSheps requested changes
Please fix merge conflicts and other issues

2024-04-03 13:50 UTC, danner26 commented
Hey @francesco-noc can you please resolve this PR issues or close the PR? Thank you

2024-04-08 19:49 UTC, danner26 commented
Uh something definitely got messed up here. You ended up making changes to a lot of files I am guessing you didnt mean to. Not sure how it happened

2024-04-10 09:46 UTC, francesco-noc commented
🤦‍♂️

2024-05-23 08:46 UTC, closed without merging