IE-2000-16PTC-G-L
netbox-community/devicetype-library pull request #1882
Opened 2024-01-25 13:39 UTC by francesco-noc

2024-01-25 15:45 UTC, DanSheps requested changes

2024-01-25 15:45 UTC, DanSheps commented on device-types/Cisco/IE-2000-16PTC-G-L.yaml
Could you add weight?

2024-01-26 12:26 UTC, lucatortiglione commented on device-types/Cisco/IE-2000-16PTC-G-L.yaml
IE-2000 18-20 ports chassis: 4.35 lb (1.97 kg)

2024-01-29 11:46 UTC, francesco-noc commented on device-types/Cisco/IE-2000-16PTC-G-L.yaml
changes made!

2024-02-15 20:52 UTC, DanSheps approved these changes

2024-02-15 20:52 UTC, merged