Cisco modules
netbox-community/devicetype-library pull request #1885
Opened 2024-01-29 14:23 UTC by francesco-noc

2024-03-07 15:40 UTC, DanSheps requested changes

2024-03-07 15:40 UTC, DanSheps commented on module-types/Cisco/N7K-SUP2.yaml
> +  - name: mgmt0
This will result in a name collision, please change this to somehow utilize the {module} to prevent this.

2024-03-22 14:05 UTC, DanSheps approved these changes

2024-03-22 14:06 UTC, DanSheps requested changes
Please remove the pickle files from your commit and fix the merge conflicts

2024-04-03 13:56 UTC, danner26 commented
@francesco-noc one more just so you have it on your list

2024-04-04 15:03 UTC, francesco-noc commented
Why are there always pickle files committed? I removed them before commit and push.
Am I missing some configuration?

2024-04-04 18:56 UTC, danner26 commented
> Why are there always pickle files committed? I removed them before commit and push. Am I missing some configuration?

You probably forked this too early and somehow got a different pickle file version. If you download the latest pickle files and add them in your commit, I think it'll fix the issue. That or start fresh from the latest master branch

2024-04-08 19:47 UTC, danner26 commented on module-types/Cisco/C9200-STACK.yaml
Why does this have nothing else on it? Is it the stacking kit that inserts into the switch?

2024-04-16 16:53 UTC, DanSheps commented on module-types/Cisco/C9200-STACK.yaml
it is a stack kit, I think it should have stack interfaces though

2024-05-23 08:46 UTC, closed without merging