Add Aruba ClearPass
netbox-community/devicetype-library pull request #1887
Opened 2024-01-29 17:54 UTC by rtm516

- ClearPass C1000 (JZ508A)
- - ClearPass C1000 (JZ508A)
- - ClearPass C1000 (JZ508A)
- - ClearPass C1000 (JZ508A)

2024-03-02 14:04 UTC, rtm516 commented
Not stale

2024-04-03 15:27 UTC, danner26 requested changes

2024-04-03 15:27 UTC, danner26 commented on device-types/HPE/ClearPass-C1000.yaml
> +    type: other
VGA is not a console port type. Please remove this

2024-04-03 15:27 UTC, danner26 commented on device-types/HPE/ClearPass-C1000.yaml
> +is_full_depth: true
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-04-03 15:27 UTC, danner26 commented on device-types/HPE/ClearPass-C2000.yaml
> +u_height: 1
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-04-03 15:27 UTC, danner26 commented on device-types/HPE/ClearPass-C2000.yaml
> +    type: other
VGA is not a console port type. Please remove this

2024-04-03 15:27 UTC, danner26 commented on device-types/HPE/ClearPass-C2010.yaml
> +is_full_depth: true
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-04-03 15:27 UTC, danner26 commented on device-types/HPE/ClearPass-C2010.yaml
> +    type: other
VGA is not a console port type. Please remove this

2024-04-03 15:27 UTC, danner26 commented on device-types/HPE/ClearPass-C3000.yaml
> +is_full_depth: true
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-04-03 15:27 UTC, danner26 commented on device-types/HPE/ClearPass-C3000.yaml
> +    type: other
VGA is not a console port type. Please remove this

2024-04-03 15:27 UTC, danner26 commented on device-types/HPE/ClearPass-C3010.yaml
> +is_full_depth: true
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-04-03 15:27 UTC, danner26 commented on device-types/HPE/ClearPass-C3010.yaml
> +    type: other
VGA is not a console port type. Please remove this

2024-04-04 14:30 UTC, merged