Add Datacom VS-1124-F
netbox-community/devicetype-library pull request #1889
Opened 2024-01-29 18:29 UTC by rtm516

2024-03-02 14:05 UTC, rtm516 commented
Not stale

2024-04-03 14:23 UTC, danner26 requested changes

2024-04-03 14:23 UTC, danner26 commented on device-types/Datacom/VS-1124-F.yaml
> +is_full_depth: true
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-04-04 14:27 UTC, danner26 approved these changes

2024-04-04 14:28 UTC, merged