Add Citrix MPX-8200
netbox-community/devicetype-library pull request #1904
Opened 2024-01-30 12:35 UTC by rtm516

2024-03-02 14:04 UTC, rtm516 commented
Not stale

2024-04-03 14:15 UTC, danner26 requested changes

2024-04-03 14:15 UTC, danner26 commented on device-types/Citrix/MPX-8200.yaml
> +    maximum_draw: 450
It appears that these are modular PSU's. Please move the definition to `module-bays` and create the associated PSUs within the module-types folder

2024-08-22 16:19 UTC, danner26 commented
Closing this since it has been incomplete for a long period of time. Feel free to work on it then reopen it again if you would like.

2024-08-22 16:19 UTC, closed without merging