Add Fortinet FSM-2000F
netbox-community/devicetype-library pull request #1905
Opened 2024-01-30 12:53 UTC by rtm516

2024-03-02 14:04 UTC, rtm516 commented
Not stale

2024-04-03 14:06 UTC, danner26 requested changes

2024-04-03 14:06 UTC, danner26 commented on device-types/Fortinet/FSM-2000F.yaml
> +is_full_depth: false
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-04-03 14:06 UTC, danner26 commented on device-types/Fortinet/FSM-2000F.yaml
> +  - name: PS21
Is this actually suppose to be called `PS21` or did you mean for it to be `PS2`?

2024-04-04 14:33 UTC, danner26 approved these changes

2024-04-04 14:34 UTC, merged