Adding template for Juniper ACX7024 router and ZPE NSR-BASE-DAC with preloaded expansion modules
netbox-community/devicetype-library pull request #1955
Opened 2024-02-22 17:38 UTC by modonovan

The purpose of this pull request is to add a new template, not yet created, for the [Juniper ACX7024 router](https://www.juniper.net/us/en/products/routers/acx-series/acx7000-family-cloud-metro-routers/acx7000-line/acx7024-acx7024x-cloud-metro-routers-datasheet.html) as well as the [ZPE Network Services Router with preloaded expansion modules](https://zpesystems.com/products/nodegrid-services-router/).

In the case of the Juniper ACX7024, I have modeled this to the best of my capability based on the Juniper product datasheet for this router and in conjunction with the ACX7100 templates that preexist. 

In the case of the ZPE NSR device, the template is modeled on the assume that;

* There is a [16 port serial console module](https://zpesystems.com/products/nodegrid-services-router/serial-expansion-card/) in Slot 1 of the device (hence the numbering ttyS1-1 etc)
* There is a [16 port ethernet switch module](https://zpesystems.com/products/nodegrid-services-router/ethernet-expansion-card/) in Slot 2 of the device (hence the numbering starting netS2-1 etc)

2024-03-07 16:12 UTC, DanSheps requested changes

2024-03-07 16:12 UTC, DanSheps commented on tests/known-modules.pickle
Remove from commit please

2024-03-07 16:12 UTC, DanSheps commented on tests/known-slugs.pickle
Remove from commit please

2024-03-19 16:43 UTC, modonovan commented on tests/known-modules.pickle
I'm a relative newbie to submitting pull requests on github.com so excuse my ignorance. I'm not sure I know how to resolve this. I've installed `gh` locally and issued a `gh pr checkout 1955`. I've then removed the files in question and did a git push. Is there something obvious I'm missing here?

2024-03-19 18:34 UTC, closed without merging

2024-03-19 18:41 UTC, modonovan commented on tests/known-slugs.pickle
Resolved by NEW PR !2011

2024-03-19 18:41 UTC, modonovan commented on tests/known-modules.pickle
Resolved by NEW PR !2011