Cisco Device: Add C9500X-28C8D
netbox-community/devicetype-library pull request #2093
Opened 2024-04-17 10:25 UTC by netravnen

Cisco Catalyst 9500X switch with 28x 40/100G QSFP28 ports
+ 8x 40/100/200/400G Gigabit Ethernet

2024-05-20 15:53 UTC, danner26 requested changes

2024-05-20 15:53 UTC, danner26 commented on device-types/Cisco/C9500X-28C8D.yaml
> +is_full_depth: true
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-05-20 15:53 UTC, danner26 commented on device-types/Cisco/C9500X-28C8D.yaml
> +    maximum_draw: 1500
These appear to be modular PSU's, is this the case? If so, these should be modelled under `module-bays` and the associated PSU's should be added to the module-types folder if they do not already exist

2024-05-20 15:53 UTC, danner26 commented on device-types/Cisco/C9500X-28C8D.yaml
> +    position: '1'
disks should not be here, please remove this

2024-10-24 21:35 UTC, harryajc approved these changes

2024-10-24 21:36 UTC, merged