added SuperServer SSG-640P-E1CR24H
netbox-community/devicetype-library pull request #2110
Opened 2024-04-23 12:35 UTC by TaLoN1x

added SuperServer SSG-640P-E1CR24H

2024-05-20 16:26 UTC, danner26 requested changes

2024-05-20 16:26 UTC, danner26 commented on device-types/Supermicro/SSG-6028R-E1CR16T.yml
> +    maximum_draw: 1000
Are these PSU's modular? If so, they should be modelled under `module-bays` and the associated PSU modules should be added to the module-types folder if they do not already exist

2024-05-20 16:26 UTC, danner26 commented on device-types/Supermicro/SSG-6029P-E1CR12T.yml
> +    maximum_draw: 1200
Are these PSU's modular? If so, they should be modelled under `module-bays` and the associated PSU modules should be added to the module-types folder if they do not already exist

2024-05-20 16:26 UTC, danner26 commented on device-types/Supermicro/SSG-640P-E1CR24H.yml
> +    maximum_draw: 1200
Are these PSU's modular? If so, they should be modelled under `module-bays` and the associated PSU modules should be added to the module-types folder if they do not already exist

2024-05-20 16:26 UTC, danner26 commented on device-types/Supermicro/SSG-640P-E1CR24H.yml
> +    comment: M-Key M.2
Right now, storage should not be modelled in this repo

2024-05-20 16:26 UTC, danner26 commented on device-types/Supermicro/SSG-6029P-E1CR12T.yml
> +    comment: M-Key M.2
Right now, storage should not be modelled in this repo

2024-05-20 16:26 UTC, danner26 commented on device-types/Supermicro/SSG-6028R-E1CR16T.yml
> +    comment: M-Key M.2
Right now, storage should not be modelled in this repo

2024-11-03 12:54 UTC, harryajc approved these changes

2024-11-03 12:55 UTC, merged