Cisco ISR 2921 Part Number Correction
netbox-community/devicetype-library pull request #2195
Opened 2024-06-12 14:43 UTC by dbreidegam

Current part number shows as ISR2921/K9, but the actual part number from Cisco is CISCO2921/K9.

2024-06-12 15:37 UTC, DanSheps requested changes
What does `show inventory` show for the PID for these devices?

2024-06-12 18:29 UTC, dbreidegam commented
Below is an example of the "show inventory" command with serial redacted.

#sh inv
NAME: "CISCO2921/K9", DESCR: "CISCO2921/K9 chassis, Hw Serial#: FJCXXXXXXXX, Hw Revision: 1.0"
PID: CISCO2921/K9      , VID: V08 , SN: FJCXXXXXXXX

2024-06-12 18:38 UTC, dbreidegam commented
2911
#sh inv
NAME: "CISCO2911/K9", DESCR: "CISCO2911/K9 chassis, Hw Serial#: FTXXXXXXXXX, Hw Revision: 1.0"
PID: CISCO2911/K9      , VID: V07 , SN: FTXXXXXXXXX

1941
#sh inv
NAME: "CISCO1941/K9", DESCR: "CISCO1941/K9 chassis, Hw Serial#: FTXXXXXXXXX, Hw Revision: 1.0"
PID: CISCO1941/K9      , VID: V05 , SN: FTXXXXXXXXX

2811
#sh inv
NAME: "2811 chassis", DESCR: "2811 chassis"
PID: CISCO2811         , VID: V03 , SN: FTXXXXXXXXX

2024-06-12 22:30 UTC, DanSheps submitted a review, later dismissed

2024-10-18 21:18 UTC, harryajc commented
Hi @dbreidegam

Please resolve the conflicting files.

Many Thanks

Harry

2025-01-09 15:57 UTC, danner26 commented
Please resubmit this PR if needed, that may be easier. I suggest you create a branch on your fork, then submit that for the PR

2025-01-09 15:57 UTC, closed without merging