update juniper MX 304
netbox-community/devicetype-library pull request #2219
Opened 2024-06-26 07:46 UTC by antoinevicot

2024-10-29 00:21 UTC, danner26 requested changes

2024-10-29 00:21 UTC, danner26 commented on elevation-images/Juniper/juniper-mx304.front.png
Please crop off the extra whitespace

2024-10-29 00:21 UTC, danner26 commented on elevation-images/Juniper/juniper-mx304.rear.png
Please crop off the extra whitespace

2025-01-21 14:32 UTC, harryajc approved these changes

2025-01-21 14:32 UTC, merged