Add equipment from VideoXLink
netbox-community/devicetype-library pull request #2253
Opened 2024-07-10 08:08 UTC by netravnen

Homepage: https://www.videoxlink.com/

Device types:
  - X2
  - X4 Mini
  - X4
  - X8

The equipment is targeted towards broadcasters.

2024-10-29 00:14 UTC, danner26 requested changes

2024-10-29 00:14 UTC, danner26 commented on elevation-images/VideoXLink/videoxlink-x4-mini.front.png
Please crop off the extra whitespace

2024-12-19 07:58 UTC, harryajc commented
Hi @netravnen 
Please complete the requested changes before marking this PR ready.

2025-01-03 15:23 UTC, harryajc approved these changes

2025-01-03 15:25 UTC, merged