Add Edgecore device types for 4630-54TE-O-AC-B, 5835-54X-O-AC-B, 7326-56X-O-AC-B
netbox-community/devicetype-library pull request #2276
Opened 2024-07-29 11:52 UTC by matofeder

2024-10-19 13:21 UTC, harryajc requested changes

2024-10-19 13:21 UTC, harryajc commented on device-types/Edgecore/4630-54TE-O-AC-B.yaml
> +comments: https://www.edge-core.com/_upload/images/2023-026-EPS201_AS4630-54TE_DS_R04_20230308.pdf
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-10-19 13:21 UTC, harryajc commented on device-types/Edgecore/5835-54X-O-AC-B.yaml
> +comments: https://www.edge-core.com/_upload/images/DCS201_AS5835-54X_DS_R06_20230717.pdf
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-10-19 13:21 UTC, harryajc commented on device-types/Edgecore/7326-56X-O-AC-B.yaml
> +comments: https://www.edge-core.com/_upload/images/DCS203_AS7326-56X_DS_R09_20230717.pdf
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-12-04 21:01 UTC, berendt commented
@matofeder Can you please add the missing information? Would be nice to have these 3 types in the device type library.

2025-03-11 20:54 UTC, closed without merging

2025-03-12 09:22 UTC, berendt commented
> I am closing this PR as it has been almost months with no response. @berendt if you wanted to create your own PR for these devices with the requested changes then i would be happy to review and merge it.

We are currently adding various Edge Core devices for a customer in our Netbox. As soon as we're done with that, I'll create a new PR so that we can also include it here in the device type library.