Ciena Devices
netbox-community/devicetype-library pull request #2331
Opened 2024-09-09 02:27 UTC by jgroom33

2024-10-09 20:48 UTC, jgroom33 commented
@danner26 Do I need to do something else with this before merge? Would you prefer the commits are squashed?

2024-10-21 08:31 UTC, harryajc commented
Hi @jgroom33 Thanks for your contribution

I am going to look at reviewing this but given the large amount of files changed this may take some time.

Harry

2024-10-21 20:31 UTC, danner26 approved these changes

2024-10-21 21:04 UTC, harryajc requested changes

2024-10-22 14:45 UTC, jgroom33 commented on device-types/Ciena/5171-platform.yaml
> +  - name: MGMT
Thanks. Updated. Oddly enough, its ports 10,11,30,31

2024-10-22 20:50 UTC, harryajc approved these changes

2024-10-22 20:50 UTC, merged

2024-10-24 03:47 UTC, CADbloke commented
FYI the pipe symbol `|` is illegal in Windows file names and will not check out.

````
C:\>cd Codez\Github\devicetype-library

C:\Codez\Github\devicetype-library>git restore --source=HEAD :/
error: invalid path 'module-types/Ciena/81(10|14)-12x25G-sfp28.yaml'
error: invalid path 'module-types/Ciena/81(10|14)-2x400G-cfp2.yaml'
error: invalid path 'module-types/Ciena/81(10|14)-2x400G-qsfpdd-macsec.yaml'
error: invalid path 'module-types/Ciena/81(10|14)-2x400G-qsfpdd.yaml'
error: invalid path 'module-types/Ciena/81(10|14)-8x100G-qsfp28.yaml'
error: invalid path 'module-types/Ciena/AC-39(26|30|32)|5142.yaml'
error: invalid path 'module-types/Ciena/AC-39(40|60).yaml'
error: invalid path 'module-types/Ciena/AC-51(62|70).yaml'
error: invalid path 'module-types/Ciena/AC-81(10|14).yaml'
error: invalid path 'module-types/Ciena/AC-81(40|90).yaml'
error: invalid path 'module-types/Ciena/DC-51(62|70).yaml'
error: invalid path 'module-types/Ciena/DC-81(10|14).yaml'
error: invalid path 'module-types/Ciena/DC-81(40|90).yaml'
````

2024-10-25 14:17 UTC, AskskwBv8T2nrm4Qnj commented
I am also facing errors related to this commit, when trying to git pull my synced repository in my IntelliJ Idea:
`POST git-upload-pack (327 bytes) From https://github.com/AskskwBv8T2nrm4Qnj/devicetype-library * branch master -> FETCH_HEAD = [up to date] master -> origin/master invalid path 'module-types/Ciena/81(10|14)-12x25G-sfp28.yaml' invalid path 'module-types/Ciena/81(10|14)-2x400G-cfp2.yaml' invalid path 'module-types/Ciena/81(10|14)-2x400G-qsfpdd-macsec.yaml' invalid path 'module-types/Ciena/81(10|14)-2x400G-qsfpdd.yaml' invalid path 'module-types/Ciena/81(10|14)-8x100G-qsfp28.yaml' invalid path 'module-types/Ciena/AC-39(26|30|32)|5142.yaml' invalid path 'module-types/Ciena/AC-39(40|60).yaml' invalid path 'module-types/Ciena/AC-51(62|70).yaml' invalid path 'module-types/Ciena/AC-81(10|14).yaml' invalid path 'module-types/Ciena/AC-81(40|90).yaml' invalid path 'module-types/Ciena/DC-51(62|70).yaml' invalid path 'module-types/Ciena/DC-81(10|14).yaml' invalid path 'module-types/Ciena/DC-81(40|90).yaml'`