Added new Device Types for AVM, Dell and Sophos
netbox-community/devicetype-library pull request #2336
Opened 2024-09-12 10:35 UTC by VentByte

AVM:
- Fritz!Box 7510

Dell:
- PowerSwitch N3248P-ON
- PowerSwitch S4128F-ON

Sophos:
- AP6 420E
- APX320
- APX530
- XGS 126
- XGS 126

2024-10-22 08:05 UTC, harryajc requested changes

2024-11-04 17:53 UTC, VentByte commented on device-types/AVM/FRITZBox-7510.yaml
> +    type: 1000base-t
I seem to have confused this with another model. It has been fixed with my latest changes

2024-11-04 18:10 UTC, VentByte commented on device-types/Dell/PowerSwitch-N3248P-ON.yaml
> +  - name: Gi1/0/2
Done

2024-11-04 18:10 UTC, VentByte commented on device-types/Dell/PowerSwitch-S4128F-ON.yaml
> +    type: iec-60320-c14
Done

2024-11-05 11:24 UTC, harryajc approved these changes

2024-11-05 11:27 UTC, harryajc commented
Hi @VentByte

Thank you for making the requested changes, However there appears to be some merge conflicts with this PR. Please can you resolve these issues so that this PR can be merged

2024-11-05 21:36 UTC, VentByte commented
Hi @harryajc
I've resolved the merge conflict, so the PR should now be ready to merge now.

2024-11-06 09:00 UTC, harryajc approved these changes

2024-11-06 09:00 UTC, merged