Add Meinberg Lantime M1000
netbox-community/devicetype-library pull request #2400
Opened 2024-10-23 10:54 UTC by pcharleston1

2024-10-23 20:42 UTC, harryajc requested changes

2024-10-23 20:42 UTC, harryajc commented on device-types/Meinberg/LANTIME M1000.yml
> +console-ports:
Hello, thank you for your contribution! In an attempt to have the most accurate and complete data we can, I have a few additional data points we would like you to add if possible.

1. Please add the `airflow` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not
2. Please add the `weight` and associated `weight_unit` data point if you have it or can find it. Often these are listed in the datasheet, but sometimes they are not

If you have any questions, please let us know :)

2024-10-25 14:19 UTC, robinreinhardt commented
duplicate of #2240
but this PR seems more comprehensive, so I would close mine.
The airflow is passive. Nothing found about the weight. But it depends on the used modules

2024-10-28 22:15 UTC, harryajc approved these changes

2024-10-28 22:15 UTC, merged