Adding Arista 722XPM series switches
netbox-community/devicetype-library pull request #2573
Opened 2024-12-18 08:34 UTC by suom1

2024-12-21 09:53 UTC, harryajc requested changes

2024-12-21 09:53 UTC, harryajc commented on device-types/Arista/CCS-722XPM-48Y4-2F.yaml
> +    poe_type: type1-ieee802.3af
These are 30w poe interface therefore you need to use 'type2-ieee802.3at'

2024-12-21 10:57 UTC, suom1 commented
Damn, mybad! Fixed now @harryajc

2024-12-22 22:08 UTC, harryajc approved these changes

2024-12-22 22:11 UTC, merged