Juniper SRX240 series device details updated.
netbox-community/devicetype-library pull request #2587
Opened 2024-12-26 15:59 UTC by cieska

2024-12-26 16:03 UTC, danner26 commented
Hello, thank you for contributing. Please resolve all failed test cases before marking this PR as ready to review. Thank you

2024-12-26 16:26 UTC, cieska commented
> Hello, thank you for contributing. Please resolve all failed test cases before marking this PR as ready to review. Thank you

Hi.
I don't understand what's wrong. Why it didn't passed the checks. Can you lead me where the issue is, please?

2024-12-26 16:41 UTC, danner26 commented
So it looks like you made this on the master branch, and I can't update the branch for you. I think you might be behind on the latest version. I suggest you reset your fork, update to the latest version, then make a new branch off of master in your fork and make your changes. Then submit that as a PR.

I am sorry I cannot assist further at the moment.

2024-12-26 18:10 UTC, harryajc commented
HI @cieska 
It looks like you are past the character limit on a single line for comments

2024-12-26 18:19 UTC, danner26 requested changes

2024-12-26 18:19 UTC, danner26 commented on device-types/Juniper/SRX240H2-POE.yaml
> +  Highest supported JUNOS software release 12.3X48-D105 (04 Aug 2020) (only with 2GB RAM). [Upgrade SRX RAM guide](https://michaeldale.com.au/archive/2014/08/23/running-junos-121x47-on-first-gen-srx2
I do not believe we should have links to unofficial websites within these files. All links should only be to manufacturer websites.

2024-12-26 18:19 UTC, danner26 commented on device-types/Juniper/SRX240H2.yaml
> +  Highest supported JUNOS software release 12.3X48-D105 (04 Aug 2020) (only with 2GB RAM). [Upgrade SRX RAM guide](https://michaeldale.com.au/archive/2014/08/23/running-junos-121x47-on-first-gen-srx2
I do not believe we should have links to unofficial websites within these files. All links should only be to manufacturer websites.

2024-12-26 18:21 UTC, danner26 commented
Hello @cieska as states on the individual files I do not think we should have links to external websites that are non-official documentation. Please remove these.

2024-12-27 21:50 UTC, harryajc commented
As these unofficial links is all that has changed with this PR I don't think it is required the comments section already has a link to the Juniper websites documentation for these devices

2024-12-27 21:50 UTC, closed without merging