Create PowerEdge_R750.yaml
netbox-community/devicetype-library pull request #735
Opened 2022-04-06 03:28 UTC by bbrk364

adding the Dell R750

2022-05-03 13:27 UTC, DanSheps requested changes

2022-05-03 13:27 UTC, DanSheps commented on device-types/Dell/PowerEdge_R750.yaml
> +    type: usb-a
We are no longer modelling USB ports unless they function solely as a console port.

The iDRAC port should be modelled as a interface as that is how it functions

2022-05-03 13:27 UTC, DanSheps commented on device-types/Dell/PowerEdge_R750.yaml
> +  - name: Optional PCIe-Gen4 8
Should be modelled as a module bay

2022-06-10 04:15 UTC, closed without merging

2023-01-04 15:00 UTC, danner26 commented
Do you still need this? @bbrk364