Create UCSB-5108-AC2-UCS 6324.yaml
netbox-community/devicetype-library pull request #736
Opened 2022-04-06 03:29 UTC by bbrk364

for Cisco UCS 5108 Blade Server Chassis w/ Cisco UCS 6324 Fabric Interconnect for Mini Express FlexPod

2022-04-10 14:57 UTC, ekrichbaum commented
I like that you modelled the IOM slots as device bays (probably should be module bays now) and the IOMs should be modelled as modules, removing those from the 5108 chassis already here.  The mini fabs should be a device/module similar to a 2208 or 2204, etc. at that point. This would allow for the ports to be added outside of the raw chassis, which is more elegant. The item up there is with the 2208 installed so could be removed and redone.

2022-04-24 06:37 UTC, bbrk364 commented
The UCS 5108 w/ two Fabric-Extender-1/UCS 6324 because of the version for Netbox =< 3.18

2022-04-24 15:05 UTC, ekrichbaum commented
You have 2 extra spaces after rj-45 on line 17 which is stopping the lint from passing.  That model still isn't quite right even with older netbox, but functional for you I would guess. Because the IOM is modular, I'm against having a device type with the components already installed for my purposes but I can see that being useful in your local case. Not sure that it belongs in the library like that because of the corner case.

2022-04-27 01:43 UTC, ryanmerolle commented
I agree with @ekrichbaum. This should not get merged as is.

2022-05-27 13:28 UTC, DanSheps requested changes
I think we are going to need to reject this.  This is just a combined SKU and not an actual individual device.  You should break out the FI and chassis if you want this merged.

2022-05-27 13:28 UTC, DanSheps commented on device-types/Cisco/UCSB-5108-AC2-UCS 6324.yaml
> +    maximum_draw: 2500
Should add module bays for this and make these modular

2022-05-27 13:28 UTC, DanSheps commented on device-types/Cisco/UCSB-5108-AC2-UCS 6324.yaml
> +    type: usb-a
This should be part of the FI child, not the chassis

2022-05-27 13:28 UTC, DanSheps commented on device-types/Cisco/UCSB-5108-AC2-UCS 6324.yaml
> +    mgmt_only: false
This should be part of the FI child.

2022-06-04 04:08 UTC, closed without merging

2023-01-04 14:59 UTC, danner26 commented
Do you still need this? @bbrk364 I see there is still a lot of changes that need to be made. If you are willing to work on it please reopen the PR and we will review it once ready