Create ProLiant_DL360_Gen10.yaml
netbox-community/devicetype-library pull request #747
Opened 2022-04-10 05:25 UTC by bbrk364

Adding a new profile for HPE DL360 Gen

2022-05-03 13:25 UTC, DanSheps requested changes

2022-05-03 13:25 UTC, DanSheps commented on device-types/HPE/ProLiant_DL360_Gen10.yaml
> +    type: usb-a
We are no longer modelling USB ports as console ports.  Please remove

2022-05-03 13:25 UTC, DanSheps commented on device-types/HPE/ProLiant_DL360_Gen10.yaml
> +    type: usb-a
Should be modelled as a IP interface as that is how this functions.

2022-05-03 13:25 UTC, DanSheps commented on device-types/HPE/ProLiant_DL360_Gen10.yaml
> +  - name: Option PCIe 3
Should be modelled as a module bay

2022-06-10 04:15 UTC, closed without merging

2023-01-04 14:58 UTC, danner26 commented
Do you still need this? @bbrk364