Create WS-C6513-E.yaml
netbox-community/devicetype-library pull request #752
Opened 2022-04-10 05:26 UTC by bbrk364

updating the module-bays

2022-05-28 03:09 UTC, DanSheps requested changes

2022-05-28 03:09 UTC, DanSheps commented on device-types/Cisco/WS-C6513-E.yaml
> +    maximum_draw: 2800
This should be made modular with appropriate PSU ports depending on the PSU inserted

2022-05-28 03:09 UTC, DanSheps commented on device-types/Cisco/WS-C6513-E.yaml
> +    mgmt_only: true
This should be part of the SUP card, should be modular and slotted in with the rest of the modules

2022-05-28 03:09 UTC, DanSheps commented on device-types/Cisco/WS-C6513-E.yaml
> +    type: rj-45
This should be part of the SUP card, should be modular and slotted in with the rest of the modules

2022-06-04 04:08 UTC, closed without merging

2023-01-04 14:58 UTC, danner26 commented
Do you still need this? @bbrk364