Create ProLiant_DL380_Gen10.yaml
netbox-community/devicetype-library pull request #780
Opened 2022-04-24 06:18 UTC by bbrk364

adding new type for DL380 Gen10

2022-04-27 07:23 UTC, weidi commented
This is in #769

2022-04-27 12:27 UTC, florianschendel commented
@weidi You have to commit your changes into your created branch

2022-05-03 13:08 UTC, DanSheps requested changes

2022-05-03 13:08 UTC, DanSheps commented on device-types/HPE/ProLiant_DL380_Gen10.yaml
> +    type: usb-a
This is not the intended use of USB ports.   They should not be modelled in this fashion unless they are truely used as a console port.

2022-05-03 13:08 UTC, DanSheps commented on device-types/HPE/ProLiant_DL380_Gen10.yaml
> +  - name: 3nd Riser/PCIe 7
This is not the intended use of device bays

2022-06-10 04:15 UTC, closed without merging