Add Dell PowerEdge C6400/C6420, R340, R420, R540, R730xd, R740xd2, T640
netbox-community/devicetype-library pull request #784
Opened 2022-04-27 11:26 UTC by rgdt

2022-05-03 13:06 UTC, DanSheps requested changes

2022-05-03 13:06 UTC, DanSheps commented on device-types/Dell/PowerEdge_C6420.yaml
> +    type: usb-a
We are no longer modelling USB ports that are not console ports as console or console server ports

2022-05-03 13:06 UTC, DanSheps commented on device-types/Dell/PowerEdge_R340.yaml
> +    type: usb-a
This should be removed

2022-05-03 13:06 UTC, DanSheps commented on device-types/Dell/PowerEdge_R540.yaml
> +    type: usb-a
See previous comment about USB ports not being modelled this way

2022-05-03 13:06 UTC, DanSheps commented on device-types/Dell/PowerEdge_R740xd2.yaml
> +    type: usb-a
See previous comment about USB ports not being modelled this way

2022-05-03 13:06 UTC, DanSheps commented on device-types/Dell/PowerEdge_T640.yaml
> +    type: usb-a
See previous comment about USB ports not being modelled this way

2022-05-03 14:30 UTC, rgdt commented
Fixed and applied changes requested according to your comments

2022-05-09 04:24 UTC, DanSheps approved these changes

2022-05-27 12:56 UTC, merged