lots of apc,cisco, dell additions
netbox-community/devicetype-library pull request #802
Opened 2022-05-09 11:35 UTC by ITJamie

lots of apc,cisco, dell additions

2022-05-09 17:07 UTC, ITJamie commented
finally got tests passing

2022-05-10 00:31 UTC, DanSheps requested changes
In addition to the comments, this conflicts with #784

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_R620xl_solidfire.yml
> +    type: usb-a
We are no longer including USB ports as "console" unless they are specifically console ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_R620xl_solidfire.yml
> +    type: usb-a
We are no longer including USB ports as "console" unless they are specifically console ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_R620xl_solidfire.yml
> +    type: iec-60320-c14
Might be better off including a module bay instead

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r200.yml
> +    type: mini-din-8
See comment about USB ports, it is equally as relevant for DIN ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r230.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r310.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r410.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r410.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r415.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r415.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r420.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r420.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r430.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r430.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r440.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r440.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r510.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r510.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r520.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r520.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r540.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r540.yml
> +power-ports:
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r710.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r710.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r715.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r715.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r730xd.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r730xd.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r820.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 00:31 UTC, DanSheps commented on device-types/Dell/PowerEdge_r820.yml
> +    type: usb-a
See comment about USB ports

2022-05-10 06:34 UTC, ITJamie commented
Cool will work on this later. Will that other dell pr be merged soon?

2022-05-27 12:56 UTC, merged