Add Mellanox SN2410.yml
netbox-community/devicetype-library pull request #870
Opened 2022-07-27 12:54 UTC by mihacucek

2022-08-03 12:17 UTC, mihacucek commented
I have updated the code with indentations that were missing...

2022-08-04 07:02 UTC, mihacucek commented
removed space ad the end reported in error

Error: types/Mellanox/SN2410.yml:323:20: [error] trailing spaces (trailing-spaces)

2022-09-02 20:55 UTC, DanSheps approved these changes

2022-09-02 20:59 UTC, DanSheps requested changes

2022-09-02 20:59 UTC, DanSheps commented on device-types/Mellanox/SN2410.yml
> +part_number: ''
Fill this in please

2022-09-02 20:59 UTC, DanSheps commented on device-types/Mellanox/SN2410.yml
> +subdevice_role: ''
This needs to be removed or set as "parent"

2022-10-10 05:17 UTC, closed without merging

2023-01-04 14:46 UTC, danner26 commented
Do you still need this? @mihacucek

2023-01-04 15:17 UTC, mihacucek commented
Hi Daniel,
The question is if project needs contributions like this :-).

I tried to contribute to the project by adding device type but got error messages all the time, regardles of correcting the mistakes.
After a few tries I stopped.

Feel free to delete or close this.

BR,
Miha

> On 4 Jan 2023, at 15:46, Daniel W. Anner ***@***.***> wrote:
> 
> 
> Do you still need this? @mihacucek <https://github.com/mihacucek>
> —
> Reply to this email directly, view it on GitHub <https://github.com/netbox-community/devicetype-library/pull/870#issuecomment-1371019762>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/APRWBZYCBRGUSKNHEKR2CGLWQWELLANCNFSM54ZQCVQQ>.
> You are receiving this because you were mentioned.
>

2023-01-04 15:30 UTC, danner26 commented
If you still want to contribute we would be happy to review it again. The original maintainers are busy but I am here to make sure the PRs get worked on
If you would like to contribute please feel free to reopen this PR, update your branch against our master, and then fix any issues. From there I will review it. If you run into issues you can also give me access to your repo, and I will be happy to correct any issues that are preventing the CI from running.