added some cisco devices, updadet ME-3600X-24TS-M
netbox-community/devicetype-library pull request #885
Opened 2022-08-22 09:39 UTC by jaannnis

Added devices:
ME-3600X-24CX-M
N540-24Z8Q2C-M
ASR-920-12CZ-A
ASR-920-12SZ-IM

removed manufacturer from model:
ME-3600X-24TS-M

2022-09-02 20:26 UTC, DanSheps requested changes

2022-09-02 20:26 UTC, DanSheps commented on device-types/Cisco/ASR-920-12SZ-IM.txt
> +    maximum_draw: 400
These are not a valid type

2022-09-02 20:26 UTC, DanSheps commented on device-types/Cisco/ME-3600X-24CX-M.txt
> +    type: PWR-ME3KX-AC
* ME PSU's are hot swappable and should be modelled as modules
* These are not a valid type

2022-09-02 20:26 UTC, DanSheps commented on device-types/Cisco/N540-24Z8Q2C-M.txt
> +	maximum_draw: 400
* Not correct type
* These are hot-swappable and should be modelled as modules

2022-10-10 05:17 UTC, closed without merging

2023-01-04 14:45 UTC, danner26 commented
Do you still need this? @jaannnis