Added a couple of devices / modules
netbox-community/devicetype-library pull request #893
Opened 2022-08-30 15:42 UTC by MrCamby

As the title says I have added a few devices and modules.

Devices
- Check Point SG7000-PLUS
- Check Point SG16200-PLUS
- Gude EMC Professional 3011
- HPE DX380 Gen10

Modules
- Check Point CPAC-8-1C-C
- Check Point CPAP-TR-100SWDM4
- Check Point CPAP-TR-10SR-C
- Cisco C9200-NM-4X
- HPE 535T
- HPE 640FLR-SFP28
- HPE 640SFP28

2022-09-02 19:27 UTC, DanSheps requested changes
Could you please break some of these out into separate PR's?

It makes it easier to review.

2022-09-02 19:27 UTC, DanSheps commented on device-types/Check Point/SG7000-PLUS.yaml
> +  description: ''
If these are modular at all, they should be broken out to modules

2022-09-02 19:27 UTC, DanSheps commented on device-types/Check Point/SG16200-PLUS.yaml
> +  description: ''
If these are modular, they should be broken out into modules

2022-09-02 19:27 UTC, DanSheps commented on device-types/Gude/emc-professional-3011.yaml
> +  description: ''
Please separate this out into a different PR

2022-09-02 19:27 UTC, DanSheps commented on device-types/HPE/DX380_Gen10.yaml
> +  allocated_draw: null
Should be modular

2022-09-02 19:27 UTC, DanSheps commented on device-types/HPE/DX380_Gen10.yaml
> +  mgmt_only: true
Should be a interface not a power port

2022-09-02 19:27 UTC, DanSheps commented on device-types/HPE/DX380_Gen10.yaml
> +slug: hpe_dx380_g10
Separate out into a different PR

Looks like you may be missing your module for PCI risers as well

2022-09-02 19:27 UTC, DanSheps commented on device-types/HPE/ProLiant_DL360_Gen10.yaml
> +comments: '[HPE DL360 Gen10 Quickspecs](https://www.hpe.com/psnow/doc/a00008159enw.pdf)'
Separate out into different PR

2022-09-02 19:27 UTC, DanSheps commented on module-types/Cisco/C9200-NM-4X.yaml
> +  description: ''
Different PR please

2022-09-02 19:27 UTC, DanSheps commented on module-types/HPE/535T.yaml
> +  mgmt_only: false
Different PR please

2022-09-02 19:27 UTC, DanSheps commented on module-types/HPE/640FLR-SFP28.yaml
> +  mgmt_only: false
Different PR please

2022-09-02 19:27 UTC, DanSheps commented on module-types/HPE/640SFP28.yaml
> +  mgmt_only: false
Different PR please

2022-10-10 05:17 UTC, closed without merging

2022-12-30 20:19 UTC, danner26 commented
Do you still need this? @MrCamby