Create C8300-6T
netbox-community/devicetype-library pull request #915
Opened 2022-09-15 16:10 UTC by davidabuckner

I forgot to update the slug to the correct model.

2022-09-15 17:06 UTC, DanSheps requested changes

2022-09-15 17:06 UTC, DanSheps commented on device-types/Cisco/C8300-6T
> +part_number: C8300-6T
This is not correct.  There is a more appopriate model number, one of:

C8300-1N1S-4T2X
C8300-1N1S-6T
C8300-2N2S-6T
C8300-2N2S-4T2X

2022-09-15 17:06 UTC, DanSheps commented on device-types/Cisco/C8300-6T
> +    maximum_draw: 650
Power supplies are modular, these should be setup as modules with each power supply as a module-type:

PWR-CC1-250WAC
PWR-CC1-500WAC
PWR-CC1-400WDC
PWR-CC1-400WHV

2022-10-24 05:23 UTC, closed without merging

2023-01-04 14:45 UTC, danner26 commented
Do you still need this? @davidabuckner

2023-01-04 15:26 UTC, danner26 commented
If you still want to contribute we would be happy to review it again. The original maintainers are busy but I am here to make sure the PRs get worked on
If you would like to contribute please feel free to reopen this PR, update your branch against our master, and then fix any issues. From there I will review it