Update ASR1001-X.yaml
netbox-community/devicetype-library pull request #926
Opened 2022-09-28 13:03 UTC by goebelmeier

Refinements for ASR1001-X

2022-09-29 14:18 UTC, goebelmeier commented
Oh, that's interesting. Should _all_ FRUs be modeled as a module? So far I understand that things like line cards are modeled as modules, but things like power supplies and fans are not.

2022-09-29 14:51 UTC, DanSheps commented
All should as they are swappable so it makes more sense to model them as modules so that they can be swapped out easily

2022-10-13 13:23 UTC, DanSheps requested changes

2022-10-13 13:23 UTC, DanSheps commented on device-types/Cisco/ASR1001-X.yaml
> +slug: asr-1001-x
We shouldn't change this

2022-10-13 13:23 UTC, DanSheps commented on device-types/Cisco/ASR1001-X.yaml
> +- name: Console
Per the bot, needs indentation.  Please fix all locations.

2022-11-21 04:06 UTC, closed without merging

2023-01-04 14:44 UTC, danner26 commented
Do you still need this? @goebelmeier