Added Meraki MR36 and MR44
netbox-community/devicetype-library pull request #943
Opened 2022-10-21 05:02 UTC by vittore

2022-11-28 05:41 UTC, vittore commented
Please add

2022-12-27 16:10 UTC, danner26 requested changes
These are not rack mountable to my knowledge. We should leave `u_height: 0` defined

2022-12-27 16:10 UTC, danner26 commented on device-types/Cisco/Meraki-MR57.yaml
> -u_height: 0
These are not rack mountable to my knowledge. We should leave `u_height: 0` defined

2022-12-27 16:10 UTC, danner26 commented on device-types/Cisco/Meraki-MR56.yaml
> -u_height: 0
These are not rack mountable to my knowledge. We should leave `u_height: 0` defined

2022-12-27 16:10 UTC, danner26 commented on device-types/Cisco/Meraki-MR53E.yaml
> -u_height: 0
These are not rack mountable to my knowledge. We should leave `u_height: 0` defined

2022-12-27 16:10 UTC, danner26 commented on device-types/Cisco/Meraki-MR53.yaml
> -u_height: 0
These are not rack mountable to my knowledge. We should leave `u_height: 0` defined

2022-12-27 16:11 UTC, danner26 commented
@vittore I also noticed your two additions are missing a newline at the end of the file. Please add a newline so validation succeeds. Thank you

2022-12-27 18:19 UTC, vittore commented
Done.

Thanks.
v.


Il giorno mar 27 dic 2022 alle ore 17:11 Daniel Anner <
***@***.***> ha scritto:

> @vittore <https://github.com/vittore> I also noticed your two additions
> are missing a newline at the end of the file. Please add a newline so
> validation succeeds. Thank you
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/netbox-community/devicetype-library/pull/943#issuecomment-1366017130>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACGV2CNJIAFEIURLJVZ2Z3WPMILZANCNFSM6AAAAAARKZXNZU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-27 18:32 UTC, danner26 approved these changes

2022-12-27 18:34 UTC, danner26 commented
Looks good! Thanks @vittore 
I will merge this soon

2022-12-27 19:02 UTC, merged