Opengear ACM7008-2-L
netbox-community/devicetype-library pull request #951
Opened 2022-11-03 14:35 UTC by cerealcable

This is essentially exactly the same as the ACM7008-2-M but doesn't have SFP ports, only ethernet.

2022-12-05 18:55 UTC, cerealcable commented
Commenting for GitHub to prevent this from staying stale.

2022-12-27 16:05 UTC, danner26 commented
Hey @cerealcable, please add a newline to the end of your file so it passes validation. Tag me once you update the PR so I can re-review! Thanks

Also, as a tip for the future, if you use pre-commit as described in the readme, it will fix these issues for you. If you have any questions feel free to let me know

2023-01-04 19:43 UTC, danner26 requested changes

2023-01-04 19:43 UTC, danner26 commented on device-types/Opengear/ACM7008-2-L.yaml
> +console-server-ports:
Is [this image](https://webobjects2.cdw.com/is/image/CDW/5651010d?$product-detail$) the right model? 

If so, it mgiht be better to lavel them exactly as they appear/show in the config

2023-01-04 19:43 UTC, danner26 commented on device-types/Opengear/ACM7008-2-L.yaml
> +power-ports:
Is [this image](https://webobjects2.cdw.com/is/image/CDW/5651010d?$product-detail$) the right model? 

If so, please make sure the power type is correct. c14 is definitely not correct.

2023-01-09 16:57 UTC, danner26 commented
Hello @cerealcable, are you able to work on this?

2023-01-21 00:26 UTC, danner26 commented
Hello @cerealcable I am reaching back out again to see if you can work on this to get it past the finish line..
If this is open another 2 weeks it will end up going stale again, and we will have to close it until you or someone else can work on it 😞

2023-02-28 04:01 UTC, closed without merging